name: Pre-Release

on:
  push:
    branches: ["main-dev"]
  pull_request:
    branches: ["main-dev"]

env:
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

permissions:
  contents: read

jobs:
  versioning:
    name: Update Version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run TinySemVer
        uses: ashvardanian/tinysemver@v3.0.0
        with:
          verbose: "true"
          version-file: "VERSION"
          update-version-in: |
            CITATION.cff:^version: (\d+\.\d+\.\d+)
            conanfile.py:version = "(\d+\.\d+\.\d+)"
            README.md:version = {(\d+\.\d+\.\d+)}
            CMakeLists.txt:VERSION (\d+\.\d+\.\d+)
          update-major-version-in: |
            include/usearch/index.hpp:^#define USEARCH_VERSION_MAJOR (\d+)
          update-minor-version-in: |
            include/usearch/index.hpp:^#define USEARCH_VERSION_MINOR (\d+)
          update-patch-version-in: |
            include/usearch/index.hpp:^#define USEARCH_VERSION_PATCH (\d+)
          dry-run: "true"

  test_ubuntu_gcc:
    name: Ubuntu (GCC)
    runs-on: ubuntu-24.04
    env:
      CC: gcc
      CXX: g++
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Pull Git submodules
        run: git submodule update --init --recursive
      - name: Build C++
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential libjemalloc-dev libomp-dev
          cmake -B build_artifacts \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            -D USEARCH_BUILD_TEST_CPP=1 \
            -D USEARCH_BUILD_BENCH_CPP=1 \
            -D USEARCH_USE_OPENMP=1 \
            -D USEARCH_USE_NUMKONG=1 \
            -D USEARCH_USE_JEMALLOC=1
          cmake --build build_artifacts --config RelWithDebInfo
      - name: Test C++
        run: build_artifacts/test_cpp

  test_ubuntu_clang:
    name: Ubuntu (Clang)
    runs-on: ubuntu-24.04
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Pull Git submodules
        run: git submodule update --init --recursive
      - name: Build C++
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential clang libomp-dev
          cmake -B build_artifacts \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            -D USEARCH_BUILD_TEST_CPP=1 \
            -D USEARCH_BUILD_BENCH_CPP=1 \
            -D USEARCH_USE_OPENMP=1 \
            -D USEARCH_USE_NUMKONG=1
          cmake --build build_artifacts --config RelWithDebInfo
      - name: Test C++
        run: build_artifacts/test_cpp

  test_macos:
    name: macOS
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Pull Git submodules
        run: git submodule update --init --recursive
      - name: Build C++
        run: |
          brew update
          brew reinstall cmake
          cmake -B build_artifacts \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            -D USEARCH_BUILD_TEST_CPP=1 \
            -D USEARCH_BUILD_BENCH_CPP=1 \
            -D USEARCH_USE_NUMKONG=1
          cmake --build build_artifacts --config RelWithDebInfo
      - name: Test C++
        run: build_artifacts/test_cpp

  test_windows_x86:
    name: Windows (X86)
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Pull Git submodules
        run: git submodule update --init --recursive
      - name: Build C++
        run: |
          cmake -B build_artifacts `
            -D CMAKE_BUILD_TYPE=RelWithDebInfo `
            -D USEARCH_BUILD_TEST_CPP=1 `
            -D USEARCH_BUILD_BENCH_CPP=1 `
            -D USEARCH_USE_NUMKONG=1
          cmake --build build_artifacts --config RelWithDebInfo
      - name: Test C++
        run: .\build_artifacts\test_cpp.exe
