name: Release

on:
  push:
    branches: ["main"]

env:
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  quality:
    name: Quality matrix
    uses: ./.github/workflows/quality.yml

  versioning:
    name: Update Version
    needs: quality
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run TinySemVer
        uses: ashvardanian/tinysemver@v3.0.0
        with:
          verbose: "true"
          version-file: "VERSION"
          update-version-in: |
            CITATION.cff:^version: (\d+\.\d+\.\d+)
            conanfile.py:version = "(\d+\.\d+\.\d+)"
            README.md:version = {(\d+\.\d+\.\d+)}
            CMakeLists.txt:VERSION (\d+\.\d+\.\d+)
          update-major-version-in: |
            include/usearch/index.hpp:^#define USEARCH_VERSION_MAJOR (\d+)
          update-minor-version-in: |
            include/usearch/index.hpp:^#define USEARCH_VERSION_MINOR (\d+)
          update-patch-version-in: |
            include/usearch/index.hpp:^#define USEARCH_VERSION_PATCH (\d+)
          dry-run: "false"
          push: "true"
          create-release: "true"
          github-token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  rebase:
    name: Rebase Dev Branch
    needs: versioning
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Perform rebase
        run: |
          git fetch origin main
          git checkout main-dev
          git rebase origin/main
      - name: Push changes
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          branch: main-dev
          unprotect_reviews: True
          force: True

  build_docs:
    name: Build Docs
    runs-on: ubuntu-24.04
    needs: versioning
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: "main"
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz dia git python3-pip
          pip install -r docs/requirements.txt
      - name: Build documentation
        run: cd docs && doxygen conf.dox && make html
      - name: Copy assets
        run: cp -r assets build/docs/html/
      - name: Compress assets
        run: tar -czvf docs.tar.gz build/docs/html/
      - name: Upload docs to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: docs.tar.gz
          update_latest_release: true

  deploy_docs_pages:
    name: Deploy GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: build_docs
    steps:
      - name: Download release assets
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: docs.tar.gz
      - name: Unpack docs
        run: tar -xf ./docs.tar.gz
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/docs/html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy_docs_vercel:
    name: Deploy Vercel
    runs-on: ubuntu-24.04
    needs: build_docs
    steps:
      - name: Notify Vercel
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DOCS_VERCEL }}
          method: "POST"
